### ISSUE TITLE
Add SUMO milestones

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/releases_insights#41]
- [x] Add milestones to the future views
- [x] Add milestones to the ICS export of the calendar
- [x] Add milestones to the JSON API

Milestones to add:
- **Friday of Beta week 1:** User affecting changes identified and provided to SUMO
- **Monday of Beta Week 3:** SUMO content uploaded for Localization
- ~~**Friday of Beta Week 4:** SUMO content Finalized~~
- ~~**Tuesday Release Week 1:** SUMO content Live.~~
